version: "3"


networks:
  backend:


services:


  nginx:
    image: nginx:stable-alpine
    container_name: nginx-blog
    restart: unless-stopped
    ports:
      - "8000:80"
      - "443:443"
    volumes:
      - ./src:/var/www/html
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php
      - mysql
    networks:
      - backend


  mysql:
    image: mysql:5.7.38
    container_name: mysql-blog
    restart: unless-stopped
    tty: true
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: blog
      MYSQL_PASSWORD: root
      MYSQL_USER: 123456
      MYSQL_ROOT_PASSWORD: 123456
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql
    volumes:
      - ./mysql/my.cnf:/etc/mysql/my.cnf
    networks:
      - backend


  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin-blog
    environment:
      PMA_HOST: mysql
      PMA_PORT: 3306
      MYSQL_ROOT_PASSWORD: 123456
    restart: unless-stopped
    ports:
      - 8080:80
    depends_on:
      - mysql
    networks:
      - backend

  php:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: php-blog
    restart: unless-stopped
    volumes:
      - ./src:/var/www/html
    ports:
      - "9000:9000"

    healthcheck:
      test: curl --fail http://localhost || exit 1
      interval: 60s
      retries: 5
      #start_period: 20s
      timeout: 10s

    networks:
      - backend




